name: SpecFlow.VisualStudio.CI 

resources:
- repo: self
  clean: true

jobs:

- template: build.yml  
  parameters:
    name: VS2019
    visualStudioVersion: '2019'
    artifactName: 'SpecFlow.VisualStudio.VS2019.CI-BuildResult'
    artifactFileName: '$(Build.ArtifactStagingDirectory)/SpecFlow.VisualStudio.VisualStudioIntegration.zip'
    pool:
      name: 'Hosted Windows 2019 with VS2019'

